test_dataset:
  dataset:
    name: paired-image-folders
    args:
      root_path_1: ./data/COD/TestDataset/COD10K/Imgs
      root_path_2: ./data/COD/TestDataset/COD10K/GT
      cache: none
      split_key: test
  wrapper:
    name: val
    args:
      inp_size: 1024
  batch_size: 1

mask_params:
  down_sample                 : [ ]    # default: [2, ]
  attn_thr                    : [ ]      # default: [0.95, ]
  pt_topk                     : [ ]   # default: [-1, ]
  recursive                   : [ ]  #default: [0, ]
  recursive_coef              : [ ]      # default: [0.3, ]
  rdd_str                     : [ ]  # default: ['', ]
  clip_use_neg_text           : [ ]         # default: [False, ]
  clip_neg_text_attn_thr      : [ ]  # default: [-1, ]
